"""OSC address map generation for osc-mcp vcv_manager compatibility."""

from typing import Any


def generate_address_map(
    patch_id: str,
    modules: list[dict],
    params_map: list[dict],
) -> dict[str, dict[str, Any]]:
    """Generate an OSC address map formatted for osc-mcp vcv_manager.

    Args:
        patch_id: The patch slug used as the URL namespace.
        modules: List of module dicts (for cross-referencing module ids).
        params_map: List of ``{label, module_id, param_id, min, max}`` dicts.

    Returns:
        OSC address map keyed by ``/vcv/<patch_slug>/<label>``.

    ## Return Format
    ```json
    {
      "/vcv/my-patch/cutoff": {"module_id": 3, "param_id": 0, "min": 0.0, "max": 1.0}
    }
    ```
    """
    return {
        f"/vcv/{patch_id}/{p['label']}": {
            "module_id": p["module_id"],
            "param_id": p["param_id"],
            "min": p.get("min", 0.0),
            "max": p.get("max", 1.0),
        }
        for p in params_map
    }


def generate_performance_sheet(
    name: str,
    persona: str,
    address_map: dict[str, dict[str, Any]],
    signal_flow: str,
    modules: list[dict],
) -> str:
    """Return a human-readable markdown performance sheet.

    The sheet lists every OSC-mapped parameter with safe ranges,
    grouped by module for live tweaking during a performance.

    Args:
        name: Patch display name.
        persona: ``"generative"`` | ``"performance"`` | ``"hybrid"``.
        address_map: The OSC address map from ``generate_address_map``.
        signal_flow: Prose description of the signal path.
        modules: List of module dicts (for grouping).

    Returns:
        Markdown string suitable for display or export.
    """
    lines = [
        f"# Performance Sheet: {name}",
        "",
        f"**Persona:** {persona}",
        "",
        "## Signal Flow",
        "",
        signal_flow,
        "",
        "## OSC-Mapped Parameters",
        "",
    ]

    # Group by module id
    mod_lookup = {m["id"]: m for m in modules}
    by_module: dict[int, list[tuple[str, dict[str, Any]]]] = {}
    for path, info in sorted(address_map.items()):
        mid = info["module_id"]
        by_module.setdefault(mid, []).append((path, info))

    for mod_id in sorted(by_module):
        mod = mod_lookup.get(mod_id, {})
        header = f"### Module {mod_id}: {mod.get('plugin', '?')}/{mod.get('model', '?')}"
        lines.append(header)
        lines.append("")
        lines.append("| OSC Path | Param ID | Safe Range | Notes |")
        lines.append("|----------|----------|------------|-------|")
        for path, info in by_module[mod_id]:
            param_range = f"[{info['min']}, {info['max']}]"
            path.split("/")[-1]
            lines.append(
                f"| `{path}` | {info['param_id']} | {param_range} | "
                f"Start at midpoint, sweep slowly |"
            )
        lines.append("")

    lines += [
        "## Performance Tips",
        "",
        "- Connect osc-mcp vcv_manager to this patch's OSC receiver before starting.",
        "- Start with all params at midpoint, then sweep live.",
        f"- For the {name} patch, the most expressive controls are the first two per module.",
        "",
        "---",
        "",
        "*Auto-generated by vcv-rack-mcp.  Fine-tune ranges per performance.*",
    ]

    return "\n".join(lines)
